### ISSUE TITLE
this project is built on unity 2018 while the vts plugin is for 2019.4.2!

### ISSUE THREAD

**Issue by hassanayoub1985** [melowntech/Vtsmageddon#2] opened 2022-02-21 17:10 UTC
Hello,
Impressive work.
I am planning to use it as a core for my demo about corona virus.
I downloaded the unity editor version which the project is built on, however the VTS plugin on play store is made for 2019.4.2 :(.
I tried to manually copy the vts folder form the project on 2019.4.2 to this project but it didn't worked.
Can you share the old plugin which work with this project or commit the plugin inside this project?
Thanks

**Comment by malytomas** [comment] 2022-03-07 10:08
Duplicate of https://github.com/melowntech/VtsDriving/issues/1

**Closed as completed by malytomas** 2022-03-07 10:08 UTC
